"""Subclass of FrameMarcas, which is generated by wxFormBuilder."""

import wx
import guiperfumes

# Implementing FrameMarcas
class ProjSisPerfumeFrameMarcas( guiperfumes.FrameMarcas ):
	def __init__( self, parent ):
		guiperfumes.FrameMarcas.__init__( self, parent )

	# Handlers for FrameMarcas events.
	def fecharFrame( self, event ):
		# TODO: Implement fecharFrame
		pass

	def adicionarMarcas( self, event ):
		# TODO: Implement adicionarMarcas
		pass

	def atualizarMarcas( self, event ):
		# TODO: Implement atualizarMarcas
		pass


