"""Subclass of FrameEssencias, which is generated by wxFormBuilder."""

import wx
import guiperfumes

# Implementing FrameEssencias
class ProjSisPerfumeFrameEssencias( guiperfumes.FrameEssencias ):
	def __init__( self, parent ):
		guiperfumes.FrameEssencias.__init__( self, parent )

	# Handlers for FrameEssencias events.
	def fecharFrame( self, event ):
		# TODO: Implement fecharFrame
		pass

	def adicionarEssencias( self, event ):
		# TODO: Implement adicionarEssencias
		pass

	def atualizarEssencias( self, event ):
		# TODO: Implement atualizarEssencias
		pass


