"""Subclass of FramePerfumesGrid, which is generated by wxFormBuilder."""

import wx
import guiperfumes

# Implementing FramePerfumesGrid
class ProjSisPerfumeFramePerfumesGrid( guiperfumes.FramePerfumesGrid ):
	def __init__( self, parent ):
		guiperfumes.FramePerfumesGrid.__init__( self, parent )

	# Handlers for FramePerfumesGrid events.
	def fecharFrame( self, event ):
		# TODO: Implement fecharFrame
		pass

	def abrirAdicionar( self, event ):
		# TODO: Implement abrirAdicionar
		pass

	def abrirSalvar( self, event ):
		# TODO: Implement abrirSalvar
		pass


